// const mockData = [
//   {
//     id: 1,
//     name: "James Bailey",
//     email: "james.bailey@xyz.com",
//     phone: "9013449479",
//     linkedin: "#",
//     status: "New Candidates",
//     date: "12/07/2024",
//     avatar: "https://i.pravatar.cc/150?img=1",
//   },
//   {
//     id: 2,
//     name: "Myron Donnelly",
//     email: "james.bailey@xyz.com",
//     phone: "9013449479",
//     linkedin: "#",
//     status: "In Progress",
//     date: "12/07/2024",
//     avatar: "https://i.pravatar.cc/150?img=2",
//   },
//   {
//     id: 3,
//     name: "Luther Cremin",
//     email: "james.bailey@xyz.com",
//     phone: "9013449479",
//     linkedin: "#",
//     status: "Completed",
//     date: "12/07/2024",
//     avatar: "https://i.pravatar.cc/150?img=3",
//   },
//   {
//     id: 4,
//     name: "Maurice Stracke",
//     email: "james.bailey@xyz.com",
//     phone: "9013449479",
//     linkedin: "#",
//     status: "On Hold",
//     date: "12/07/2024",
//     avatar: "https://i.pravatar.cc/150?img=4",
//   },
//   {
//     id: 5,
//     name: "Iris Funk",
//     email: "james.bailey@xyz.com",
//     phone: "9013449479",
//     linkedin: "#",
//     status: "In Progress",
//     date: "12/07/2024",
//     avatar: "https://i.pravatar.cc/150?img=5",
//   },
//   {
//     id: 6,
//     name: "Lynda Dare",
//     email: "james.bailey@xyz.com",
//     phone: "9013449479",
//     linkedin: "#",
//     status: "New Candidates",
//     date: "12/07/2024",
//     avatar: "https://i.pravatar.cc/150?img=6",
//   },
//   {
//     id: 7,
//     name: "Christy Johnson-Yost",
//     email: "james.bailey@xyz.com",
//     phone: "9013449479",
//     linkedin: "#",
//     status: "Completed",
//     date: "12/07/2024",
//     avatar: "https://i.pravatar.cc/150?img=7",
//   },
// ];
